exports.status_NEW = "NEW"
exports.status_ACCEPTED = "ACCEPTED"
exports.status_REJECTED = "REJECTED"
exports.status_READY = "READY"
exports.status_DELIVERING = "DELIVERING"
exports.status_COMPLETED = "COMPLETED"
